[package]
name = "escrow-vault"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "escrow_vault"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.18.0"
anchor-spl = "0.18.0"
spl-token-vault = { version="0.0.1", features = [ "no-entrypoint" ] }
spl-token = {version = "3.1.1", features = ["no-entrypoint"]}
